---
title: NEW TITLE
date: 2021-05-17
---
theme: minima

author: Some GitHub User
email: my-email@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for my new site here. 

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  sejo6549 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
